#!/usr/bin/python3
import os
import openai
import sys

arr = sys.argv
arr.pop(0)
prmpt = ""
for t in arr:
  prmpt = prmpt + " " + t

openai.api_key = "your api key"

response = openai.Completion.create(
  model="text-davinci-003",
  prompt=prmpt,
  temperature=0.7,
  max_tokens=256,
  top_p=1,
  frequency_penalty=0,
  presence_penalty=0
)

print(response.choices[0].text)
